### ISSUE TITLE
Idea: Provide a multi-targeted NuGet package

### ISSUE THREAD

**Issue by marceln-gh** [rena0157/mapr#15]
Hi,

The current NuGet package depends on .NET 6.
At the moment I'm not yet able to use .NET 6 for all my clients but I would like to introduce this library in the existing code base.

Would you consider creating a multi-targeted NuGet package that can be used in:
- netcoreapp3.1 (or netstandard2.1)
- net5.0
- net6.0

(https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file)

**Comment by rena0157** [comment]
Yea I was thinking that would be a good ideas as well. Just added netstandard 2.1, net 5.0 and net6.0 in #16. Let me know if you have any comments in the PR.
